@Test                                                                                                  @Test                                                                                               
public void testResourceToString_NullResource_WithClassLoader() throws Exception {                     public void testResourceToString_NullResource_WithClassLoader() throws Exception {                  
boolean exceptionOccurred = false;                                                                     boolean exceptionOccurred = false;                                                                  
try {                                                                                                  try {                                                                                               
IOUtils.resourceToString(null, StandardCharsets.UTF_8, ClassLoader.getSystemClassLoader());            IOUtils.resourceToString(null, StandardCharsets.UTF_8, ClassLoader.getSystemClassLoader());         
fail();                                                                                                fail();                                                                                             
} catch (NullPointerException npe) {                                                                 | } catch (final NullPointerException npe) {                                                          
exceptionOccurred = true;                                                                              exceptionOccurred = true;                                                                           
assertNotNull(npe);                                                                                    assertNotNull(npe);                                                                                 
}                                                                                                      }                                                                                                   
assertTrue(exceptionOccurred);                                                                         assertTrue(exceptionOccurred);                                                                      
}                                                                                                      }                                                                                                   
