public void testAddEventListenerThrowsException() {
    final ExceptionEventSource src = new ExceptionEventSource();
    try {
        EventUtils.addEventListener(src, ActionListener.class, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                // Do nothing!
            }
        });
        fail("Add method should have thrown an exception, so method should fail.");
    } catch (RuntimeException e) {
    }
}