// -----------------------------------------------------------------------
public void testIndexOf_ThrowableClass() {
    assertEquals(-1, ExceptionUtils.indexOfThrowable(null, null));
    assertEquals(-1, ExceptionUtils.indexOfThrowable(null, NestableException.class));
    assertEquals(-1, ExceptionUtils.indexOfThrowable(withoutCause, null));
    assertEquals(-1, ExceptionUtils.indexOfThrowable(withoutCause, ExceptionWithCause.class));
    assertEquals(-1, ExceptionUtils.indexOfThrowable(withoutCause, NestableException.class));
    assertEquals(0, ExceptionUtils.indexOfThrowable(withoutCause, ExceptionWithoutCause.class));
    assertEquals(-1, ExceptionUtils.indexOfThrowable(nested, null));
    assertEquals(-1, ExceptionUtils.indexOfThrowable(nested, ExceptionWithCause.class));
    assertEquals(0, ExceptionUtils.indexOfThrowable(nested, NestableException.class));
    assertEquals(1, ExceptionUtils.indexOfThrowable(nested, ExceptionWithoutCause.class));
    assertEquals(-1, ExceptionUtils.indexOfThrowable(withCause, null));
    assertEquals(0, ExceptionUtils.indexOfThrowable(withCause, ExceptionWithCause.class));
    assertEquals(1, ExceptionUtils.indexOfThrowable(withCause, NestableException.class));
    assertEquals(2, ExceptionUtils.indexOfThrowable(withCause, ExceptionWithoutCause.class));
    assertEquals(-1, ExceptionUtils.indexOfThrowable(withCause, Exception.class));
}