public void testMoveDirectory_Errors() throws Exception {
    try {
        FileUtils.moveDirectory(null, new File("foo"));
        fail("Expected IllegalArgumentException when source is null");
    } catch (IllegalArgumentException e) {
    }
    try {
        FileUtils.moveDirectory(new File("foo"), null);
        fail("Expected IllegalArgumentException when destination is null");
    } catch (IllegalArgumentException e) {
    }
    try {
        FileUtils.moveDirectory(new File("nonexistant"), new File("foo"));
        fail("Expected FileNotFoundException for source");
    } catch (FileNotFoundException e) {
    }
    File testFile = new File(getTestDirectory(), "testMoveDirectoryFile");
    createFile(testFile, 0);
    try {
        FileUtils.moveDirectory(testFile, new File("foo"));
        fail("Expected IOException when source is not a directory");
    } catch (IOException e) {
    }
    File testSrcFile = new File(getTestDirectory(), "testMoveDirectorySource");
    File testDestFile = new File(getTestDirectory(), "testMoveDirectoryDest");
    testDestFile.mkdir();
    try {
        FileUtils.moveDirectory(testSrcFile, testDestFile);
        fail("Expected IOException when dest already exists");
    } catch (IOException e) {
    }
}