private void assertGetClassThrowsException(String className, Class<?> exceptionType) throws Exception {
    try {
        ClassUtils.getClass(className);
        fail("ClassUtils.getClass() should fail with an exception of type " + exceptionType.getName() + " when given class name \"" + className + "\".");
    } catch (Exception e) {
        assertTrue(exceptionType.isAssignableFrom(e.getClass()));
    }
}